apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: devops
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.devops.svc.cluster.local:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "15s"
          httpMethod: "POST"

